# Generated by Django 3.2.6 on 2021-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
