# Generated by Django 3.2.6 on 2021-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.URLField(default='', max_length=2000),
        ),
    ]
