# Generated by Django 3.2.6 on 2021-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
