# Generated by Django 3.2.6 on 2021-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
