# Generated by Django 3.2.6 on 2021-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_is_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('img_url', models.URLField(default='', max_length=2000)),
                ('desc', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Gromming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('img_url', models.URLField(default='', max_length=2000)),
                ('desc', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('img_url', models.URLField(default='', max_length=2000)),
                ('desc', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('img_url', models.URLField(default='', max_length=2000)),
                ('desc', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Clothing',
        ),
    ]
