# Generated by Django 3.2.6 on 2021-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210812_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('img_url', models.URLField(default='', max_length=2000)),
                ('desc', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gromming',
            new_name='Daliy_Use',
        ),
    ]
